apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build
  namespace: git-clone
spec:
  params:
    - name: contextDir
      type: string
    - name: dockerfilePath
      type: string
    - name: imageName
      type: string
      description: The name of the Docker image to build
  steps:
    - name: build
      image: docker:20.10.9
      command: ["/bin/sh"]
      args: ["-c", "docker build -t ${imageName} -f ${dockerfilePath} ${contextDir}"]
