apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-repo
  namespace: git-clone
spec:
  params:
  - name: git-url
    type: string
    description: The URL of the Git repository to clone
  - name: git-branch
    type: string
    default: main
    description: The branch to checkout after cloning
  - name: output-dir
    type: string
    description: The directory to output the cloned repository to
  steps:
  - name: clone
    image: alpine/git
    command:
    - sh
    - -c
    - |
      git clone --branch $(params.git-branch) $(params.git-url) /workspace/source
    workingDir: /workspace
  - name: copy
    image: ubuntu
    command:
    - sh
    - -c
    - |
      cp -r /workspace/source $(params.output-dir)
    workingDir: /workspace
