apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push
  namespace: git-clone
spec:
  steps:
    - name: push-image
      image: alpine
      command:
        - sh
      args:
        - -c
        - echo "Hello Push Task!"
 
