apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials # The name of the secret
  namespace: git-clone # The namespace of the secret
  annotations: 
    tekton.dev/docker-0: https://index.docker.io
type: kubernetes.io/basic-auth
stringData:
  username: "<USERNAME>" # Your DockerHub username goes here
  password: "<PASSWORD>" # Your DockerHub password goes here


 
