apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tekton-pipeline 
  namespace: git-clone
spec:
  params:
    - name: IMAGE
      description: Image description
      type: string
      default: https://hub.docker.com/repository/docker/limarktest/tekton-nodejs
    - name: TAG
      description: Preferred tag
      default: latest
  workspaces:
    - name: tekton-workspace
  tasks:
    - name: fetch-repository 
      taskRef:
        name: git-clone 
      workspaces:
        - name: output
          workspace: tekton-workspace
      params:
        - name: url
          value: https://github.com/dinushchathurya/tekton-docker-push.git
        - name: subdirectory
          value: ""
        - name: deleteExisting
          value: "true"
    - name: build-push-image 
      taskRef:
        name: buildah 
      runAfter:
        - fetch-repository 
      workspaces:
        - name: source
          workspace: tekton-workspace
      params:
        - name: IMAGE
          value: "$(params.IMAGE):$(params.TAG)" 
        - name: CONTEXT
          value: "app" 
        - name: FORMAT
          value: "docker"