apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tekton-pipelinerun-
  namespace: git-clone
spec:
  serviceAccountName: dockerhub-service-account
  pipelineRef:
    name: tekton-pipeline 
  podTemplate:
    securityContext:
      fsGroup: 65532 
  params:
  - name: repo-url
    value: https://github.com/dinushchathurya/tekton-docker-push
  - name: image-reference
    value: limarktest/tekton-nodejs
  - name: image-tag
    value: latest
  workspaces:
    - name: tekton-workspace 
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 25Gi




              
