apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: my-pipeline
  namespace: git-clone
spec:
  params:
    - name: url
      type: string
    - name: revision
      type: string
    - name: path
      type: string
      default: ""
  tasks:
    - name: git-checkout
      taskRef:
        name: git-checkout
      params:
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
        - name: path
          value: $(params.path)
    - name: build
      taskRef:
        name: build
      runAfter: [git-checkout]
    - name: push
      taskRef:
        name: push
      runAfter: [build]
        