apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-buildah-template
  namespace: git-clone
spec:
  params:
    - name: gitrevision
      description: The git revision
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: tekton-pipelinerun-
        namespace: git-clone
      spec:
        serviceAccountName: dockerhub-service-account
        pipelineRef:
          name: tekton-pipeline 
        podTemplate:
          securityContext:
            fsGroup: 65532 
        params:
          - name: repo-url
            value: "$(tt.params.gitrepositoryurl)"
          - name: image-reference
            value: limarktest/tekton-nodejs
          - name: image-tag
            value: "$(tt.params.gitrevision)"
        workspaces:
          - name: tekton-workspace 
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 25Gi